#!/usr/bin/env python
from befunge.interpreter import Interpreter 
import sys

with open(sys.argv[1], 'r') as f:
    code = f.read() 

b = Interpreter(code)
b.execute(debug=True if sys.argv[2] == "True" else False) 
